from typing import List, TypedDict

class AgentState(TypedDict):
    """
    Represents the state of our agentic graph.
    Passed between nodes to track historical execution data.
    """
    query: str                  # The original or rewritten user question
    retrieved_docs: List[str]   # Text chunks fetched from Qdrant
    generation: str             # Final answer generated by Gemini
    steps: List[str]            # Track logs of visited nodes for debugging